var treeData = [{
	"id": 1,
	"pId": 0,
	"name": "武汉市公安消防支队（3/4）",
	"icon": "assets/images/icon/level1.png"
}, {
	"id": 2,
	"pId": 1,
	"name": "鄂A10020",
	"iconSkin": "car",
	"icon": "assets/images/icon/car-green.png"
}, {
	"id": 3,
	"pId": 1,
	"name": "江岸大队（1/1)",
	"icon": "assets/images/icon/level2.png"
}, {
	"id": 4,
	"pId": 3,
	"name": "鄂A10020",
	"iconSkin": "car",
	"icon": "assets/images/icon/car-red.png"
}, {
	"id": 5,
	"pId": 3,
	"name": "江岸中队（1/1)",
	"icon": "assets/images/icon/level3.png"
}, {
	"id": 6,
	"pId": 5,
	"name": "鄂A10020",
	"iconSkin": "car",
	"icon": "assets/images/icon/car-blue.png"
},  {
	"id": 7,
	"pId": 5,
	"name": "天地小型站（0/1）",
	"icon": "assets/images/icon/level4.png"
}, {
	"id": 8,
	"pId": 7,
	"name": "鄂A10020",
	"iconSkin": "car",
	"icon": "assets/images/icon/car-gray.png"
}, {
	"id": 9,
	"pId": 5,
	"name": "天地小型站（1/1）",
	"icon": "assets/images/icon/level4.png"
}, {
	"id": 10,
	"pId": 9,
	"name": "鄂A10020",
	"iconSkin": "car",
	"icon": "assets/images/icon/car-green.png"
}, {
	"id": 11,
	"pId": 1,
	"name": "硚口大队（1/1)",
	"icon": "assets/images/icon/level2.png"
}, {
	"id": 12,
	"pId": 11,
	"name": "鄂A10020",
	"iconSkin": "car",
	"icon": "assets/images/icon/car-green.png"
}, {
	"id": 13,
	"pId": 11,
	"name": "硚口中队（1/1)",
	"icon": "assets/images/icon/level3.png"
}, {
	"id": 14,
	"pId": 13,
	"name": "鄂A10020",
	"iconSkin": "car",
	"icon": "assets/images/icon/car-green.png"
},  {
	"id": 15,
	"pId": 13,
	"name": "天地小型站（0/1）",
	"icon": "assets/images/icon/level4.png"
}, {
	"id": 16,
	"pId": 15,
	"name": "鄂A10020",
	"iconSkin": "car",
	"icon": "assets/images/icon/car-gray.png"
}, {
	"id": 16,
	"pId": 13,
	"name": "天地小型站（1/1）",
	"icon": "assets/images/icon/level4.png"
}, {
	"id": 17,
	"pId": 16,
	"name": "鄂A10020",
	"iconSkin": "car",
	"icon": "assets/images/icon/car-green.png"
}]