var treeData = [{
	"id": 1,
	"pid": 0,
	"name": "武汉市公安消防支队（3/4）",
	"icon": "assets/images/icon/level1.png",
	"nocheck": true,
	"click": false
}, {
	"id": 2,
	"pid": 1,
	"name": "鄂A10020",
	"iconSkin": "car",
	"icon": "assets/images/icon/car-green.png"
}, {
	"id": 3,
	"pid": 1,
	"name": "江岸大队（1/1)",
	"icon": "assets/images/icon/level2.png",
	"nocheck": true,
	"click": false
}, {
	"id": 4,
	"pid": 3,
	"name": "鄂A20020",
	"iconSkin": "car",
	"icon": "assets/images/icon/car-red.png"
}, {
	"id": 5,
	"pid": 3,
	"name": "江岸中队（1/1)",
	"icon": "assets/images/icon/level3.png",
	"nocheck": true,
	"click": false
}, {
	"id": 6,
	"pid": 5,
	"name": "鄂A30020",
	"iconSkin": "car",
	"icon": "assets/images/icon/car-blue.png"
},  {
	"id": 7,
	"pid": 5,
	"name": "天地小型站（0/1）",
	"icon": "assets/images/icon/level4.png",
	"nocheck": true,
	"click": false
}, {
	"id": 8,
	"pid": 7,
	"name": "鄂A40020",
	"iconSkin": "car",
	"icon": "assets/images/icon/car-gray.png"
}, {
	"id": 9,
	"pid": 5,
	"name": "天地小型站（1/1）",
	"icon": "assets/images/icon/level4.png",
	"nocheck": true,
	"click": false
}, {
	"id": 10,
	"pid": 9,
	"name": "鄂A50020",
	"iconSkin": "car",
	"icon": "assets/images/icon/car-green.png"
}, {
	"id": 11,
	"pid": 1,
	"name": "硚口大队（1/1)",
	"icon": "assets/images/icon/level2.png",
	"nocheck": true,
	"click": false
}, {
	"id": 12,
	"pid": 11,
	"name": "鄂A60020",
	"iconSkin": "car",
	"icon": "assets/images/icon/car-green.png"
}, {
	"id": 13,
	"pid": 11,
	"name": "硚口中队（1/1)",
	"icon": "assets/images/icon/level3.png",
	"nocheck": true,
	"click": false
}, {
	"id": 14,
	"pid": 13,
	"name": "鄂A70020",
	"iconSkin": "car",
	"icon": "assets/images/icon/car-green.png"
},  {
	"id": 15,
	"pid": 13,
	"name": "天地小型站（0/1）",
	"icon": "assets/images/icon/level4.png",
	"nocheck": true,
	"click": false
}, {
	"id": 16,
	"pid": 15,
	"name": "鄂A80020",
	"iconSkin": "car",
	"icon": "assets/images/icon/car-gray.png"
}, {
	"id": 16,
	"pid": 13,
	"name": "天地小型站（1/1）",
	"icon": "assets/images/icon/level4.png",
	"nocheck": true,
	"click": false
}, {
	"id": 17,
	"pid": 16,
	"name": "鄂A90020",
	"iconSkin": "car",
	"icon": "assets/images/icon/car-green.png"
}]